# This is a "normal" job.
universe = vanilla

# If any information about this submission is written
# as output to standard output or standard error,
# where should it be saved?
job = cyclus_test
executable = $(job).sh
output = $(job).out
error = $(job).err

# Where to write a log of your jobs' statuses.
log = $(job).log

# All interactive jobs (compiling MatLab, R, Python, etc.) 
# are pointed to our MatLab build machines
requirements = (OpSysAndVer =?= "SL6") && Arch == "X86_64"

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate your tarball of compiling sources here, to be transfered
# to the build machine when your interactive session starts.
# Make sure to create a different tarball of the files you want
# transfered back to the submit node when you're done compiling.
transfer_input_files = cyclus-build.tar.gz

request_cpus = 1
request_memory = 500
request_disk = 5242880

# We don't want email about our jobs. (If you do, let us know,
# there may be some additional configuration necessary.)
notification = never

queue